### ISSUE TITLE
Design Rewards section in Profile page

### ISSUE THREAD

**Issue by dwip708** [dwip708/EcoFusion#11]
This is the current page.

![image](https://github.com/user-attachments/assets/1d8c1f9d-997a-457a-9ad4-6e0962063612)

Design Rewards Component in the ProfileComponents folder and add in Profile.js like Personal Information is added. Rewards are like simple coupons like in Google Pay/ Amazon pay rewards like coupons from abc websites. 

Just make the reward card div and arrange with proper styles in rewards section. Check if it is current or expired. Every reward will have issuedate and expiredstatus beside other details. Take some dummy rewards as a list and display. If no rewards or no non-expired rewards, show appropriate message properly with styles.  Initially show top few rewards, and all show more button too. It should not exceed the height of screen, make it scrollable after show all.

**Comment by JelenaDinic** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by dwip708** [comment]
sure.

**Comment by dwip708** [comment]
@JelenaDinic are you still working on this issue?

**Comment by JelenaDinic** [comment]
@dwip708 Yes. It will be done in few days. Possibly tomorrow

**Comment by JelenaDinic** [comment]
@dwip708 can you add me as a contributor so I can push my changes? :)
