### ISSUE TITLE
Improve Contact us Page

### ISSUE THREAD

**Issue by dwip708** [dwip708/EcoFusion#12]
I am providing a sample of contact us page
![image](https://github.com/user-attachments/assets/4b969285-5d59-4df3-821a-78674c2a235a)

This is just a sample. Edit the page and style similarly to add these details besides the form.
Have sections like need help with order, need help with account, etc, relavant to an e-commerce website.

**Comment by aniruddhaadak80** [comment]
I am working on this issue . Please assign this to me @dwip708

**Comment by dwip708** [comment]
@aniruddhaadak80 assigning you. In case you face any issue with code, comment here.

**Comment by aniruddhaadak80** [comment]
Thanks for merging @dwip708 .

**Comment by dwip708** [comment]
![image](https://github.com/user-attachments/assets/4310c536-8daf-448c-9334-a948a1724d64)

This page needs proper styling. The flex is not properly styled.  @aniruddhaadak80 please add appropriate styles and raise another PR. Keep some side margins as in other pages. And fit it in the same page without need of scrolling.

**Comment by aniruddhaadak80** [comment]
okey @dwip708 .I am fixing this .

**Comment by dwip708** [comment]
The 2 PRs did not solve the styling issue, hence I have reverted both the PRs.
Attach a screenshot with the PR if you work on this issue. The form and the assisting texts should be in 2 columns side by side like the sample image. Expecting a similar styling.

**Comment by dwip708** [comment]
@aniruddhaadak80 are you still working on it?

**Comment by spudoodle** [comment]
Hey, I would like to work on this.

**Comment by dwip708** [comment]
@slusy Sure... assigning you
