### ISSUE TITLE
Improve empty cart style

### ISSUE THREAD

**Issue by dwip708** [dwip708/EcoFusion#15]
This is the current empty cart page

![image](https://github.com/user-attachments/assets/071b5ce4-86c4-40fa-91fc-3b7e3de73527)

Style it so that it looks better and more attractive.

**Comment by dwip708** [comment]
@AqibAliMughal This is not responsive on changing screen size. Can you sort the issue?

**Comment by AqibAliMughal** [comment]
Yeah sure, please assign it to me again. @dwip708

**Comment by AqibAliMughal** [comment]
Hi @dwip708
Please have a look at the recent PR. 
I have tested some of the devices and working fine such as Tablet/ Pixel 7, & Iphone14 Max.
