### ISSUE TITLE
Design Profile Page

### ISSUE THREAD

**Issue by dwip708** [dwip708/EcoFusion#3]
Need a similar profile page, not exactly copy, the structure should be similar. Just add side buttons as shown here (non functional) for addresss and all.

![image](https://github.com/user-attachments/assets/bb9f095d-090e-4af6-8105-c7f01a321442)

Profile page should have the 2 columns. Left one with account details and the buttons.
Right one for loading the component based on button pressed. 

Make the overall Profile page, left column non-functional buttons, right pane only personal information part. Whatever button be clicked, render the personal information component only. 

Style appropriately.

**Comment by 10m4y** [comment]
@dwip708 I will be keen to work on this issue can u pls assign it to me

**Comment by dwip708** [comment]
@cypher4802 are you working on it?
